### ISSUE TITLE
Taurus run failed - Could not find location at path: Blazedemo.jmx

### ISSUE THREAD

**Issue by hoadoantn** [algattik/jmeter-extension#1]
I configured YAML as following"
```
execution:
- scenario:
    script: Blazedemo.jmx
  concurrency: 15
  iterations: 3
  ramp-up: 15s

reporting:
- module: junit-xml
  filename: taurus-output/TEST-Taurus.xml

```
I pushed Blazedemo.jmx into root repo however it seems that search folder is not Azure git repo?

![TarusRunFailed](https://user-images.githubusercontent.com/50944376/81532522-bc2e2000-938e-11ea-9618-26d6b40754c6.PNG)

Please give me the advice

Thanks
